#!/bin/bash

OPTS="$@"

cmake \
-DCMAKE_C_COMPILER="icc" \
-DCMAKE_CXX_COMPILER="icpc" \
-DCMAKE_C_FLAGS="-O3 -g -fPIC -DSQLITE_DISABLE_INTRINSIC" \
-DCMAKE_CXX_FLAGS="-O3 -g -fPIC -DSQLITE_DISABLE_INTRINSIC" \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
${OPTS} \
..
